equals(lengthOf(line(e,f)),lengthOf(line(a,c))).
equals(measureOf(angle(d,a,b)),measureOf(angle(d,a,c))).
isMidpointOf(point(d),line(e,c)).
isMidpointOf(point(d),line(g,f)).
line(a,b).
line(a,d).
line(a,f).
line(b,c).
line(c,a).
line(c,e).
line(d,c).
line(d,e).
line(d,f).
line(d,f).
line(d,g).
line(f,e).
line(f,g).
on_same_line(a,d,f).
on_same_line(a,d,g).
on_same_line(a,f,g).
on_same_line(b,c,d).
on_same_line(b,c,e).
on_same_line(b,d,e).
on_same_line(c,d,e).
on_same_line(d,f,g).
point(a).
point(b).
point(c).
point(d).
point(e).
point(f).
point(g).
pointLiesOnLine(d,line(b,c)).
pointLiesOnLine(e,line(d,c)).
pointLiesOnLine(f,line(a,d)).
pointLiesOnLine(f,line(a,d)).
pointLiesOnLine(g,line(d,f)).
pointPosition(a,1912,10).
pointPosition(b,10,10).
pointPosition(c,1358,1236).
pointPosition(d,799,728).
pointPosition(e,240,220).
pointPosition(f,1586,220).
pointPosition(g,12,1236).
quadrilateral(a,b,e,f).
quadrilateral(a,b,g,c).
quadrilateral(a,c,g,b).
quadrilateral(a,c,g,e).
quadrilateral(a,e,g,c).
quadrilateral(a,f,e,b).
quadrilateral(b,a,c,g).
quadrilateral(b,a,f,e).
quadrilateral(b,e,f,a).
quadrilateral(b,f,c,g).
quadrilateral(b,g,c,a).
quadrilateral(b,g,c,f).
quadrilateral(c,a,b,g).
quadrilateral(c,a,e,g).
quadrilateral(c,f,b,g).
quadrilateral(c,f,e,g).
quadrilateral(c,g,b,a).
quadrilateral(c,g,b,f).
quadrilateral(c,g,e,a).
quadrilateral(c,g,e,f).
quadrilateral(e,a,c,g).
quadrilateral(e,b,a,f).
quadrilateral(e,f,a,b).
quadrilateral(e,f,c,g).
quadrilateral(e,g,c,a).
quadrilateral(e,g,c,f).
quadrilateral(f,a,b,e).
quadrilateral(f,b,g,c).
quadrilateral(f,c,g,b).
quadrilateral(f,c,g,e).
quadrilateral(f,e,b,a).
quadrilateral(f,e,g,c).
quadrilateral(g,b,a,c).
quadrilateral(g,b,f,c).
quadrilateral(g,c,a,b).
quadrilateral(g,c,a,e).
quadrilateral(g,c,f,b).
quadrilateral(g,c,f,e).
quadrilateral(g,e,a,c).
quadrilateral(g,e,f,c).
triangle(a,b,c).
triangle(a,b,c).
triangle(a,b,d).
triangle(a,b,e).
triangle(a,b,f).
triangle(a,b,g).
triangle(a,c,d).
triangle(a,c,e).
triangle(a,c,f).
triangle(a,c,g).
triangle(a,d,e).
triangle(a,e,f).
triangle(a,e,g).
triangle(b,c,f).
triangle(b,c,g).
triangle(b,d,f).
triangle(b,d,g).
triangle(b,e,f).
triangle(b,e,g).
triangle(b,f,g).
triangle(c,d,f).
triangle(c,d,g).
triangle(c,e,f).
triangle(c,e,g).
triangle(c,f,g).
triangle(d,e,f).
triangle(d,e,g).
triangle(e,f,g).